# Config file for automatic testing at travis-ci.org
language: c

sudo: false

env:
  - MC_PYTHON=2.7
  - MC_PYTHON=3.5
  - MC_PYTHON=3.6
  - MC_PYTHON=3.7

os:
    - linux
    - osx

before_install:
    - |-
      miniconda_os=Linux
      if ["$TRAVIS_OS_NAME" == "osx"]; then
        miniconda_os=MacOSX
        HOMEBREW_NO_AUTO_UPDATE=1 brew install md5sha1sum
      fi
      wget http://repo.continuum.io/miniconda/Miniconda3-latest-${miniconda_os}-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda info -a

install:
    - conda create -q -n test_env python=$MC_PYTHON six pytest
    - source activate test_env
    - python -m pip install .

script:
    - pytest
