# Config file for automatic testing at travis-ci.org
language: c

sudo: false

env:
  - MC_PYTHON=3.6
  - MC_PYTHON=3.7
  - MC_PYTHON=3.8
  - MC_PYTHON=3.9

os:
    - linux
    - osx

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]];   then wget http://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;  fi
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda info -a

install:
    - conda create -q -n test_env python=$MC_PYTHON six pytest
    - source activate test_env
    - python -m pip install .

script:
    - pytest
