
environment:

  matrix:

     - PYTHON: "C:\\Python36-x64"
     - PYTHON: "C:\\Python37-x64"
     - PYTHON: "C:\\Python38-x64"

install:
    - "%PYTHON%\\python.exe -m pip install wheel pip six pywin32 pytest"
    - "%PYTHON%\\python.exe setup.py install"

build: off

test_script:
    - cd tests
    - "%PYTHON%\\python.exe -m pytest"
