environment:
  matrix:
    - PYTHON: "C:\\Python27-x64"
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36-x64"

install:
    - pip install six pywin32 pytest
    - python setup.py install

build: off

test_script:
    - cd tests
    - pytest
